### ISSUE TITLE
Logseq 0.9.6 - Plugin always fails with 'is not a valid UUID string'

### ISSUE THREAD

**Issue by adxsoft** [vipzhicheng/logseq-plugin-copy-ref-to-journal#17]
This plugin is not working anymore for me using Logseq 0.9.6 on Mac Desktop

UI window comes up as expected when I click OK button get this trace in the developer log

`
index.html:1 Uncaught (in promise) **Error:  is not a valid UUID string**.

    at $logseq$sdk$utils$uuid_or_throw_error$$ (ui.cljs:31:16)

    at $logseq$api$block$get_block$$ (block.cljs:13:3)

    at Kr.<anonymous> (api.cljs:690:8)

    at Kr.Lt (lsplugin.core.js:2:58291)

    at Kr.<anonymous> (lsplugin.core.js:2:94523)

    at a.emit (lsplugin.core.js:2:26980)

    at Vt.<anonymous> (lsplugin.core.js:2:89915)

    at lsplugin.core.js:2:62297

    at Array.forEach (<anonymous>)

    at Vt.listener (lsplugin.core.js:2:62282)`

**Comment by adxsoft** [comment]
Works in 0.9.8
Issue Closed
